2025-08-12 06:32:01.379 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2025-08-12 06:32:01.421 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=1 from 2025-08-12 11:23:45.881583)
2025-08-12 06:32:04.161 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)

2025-08-12 06:32:44.662 WARNING (zeroconf-ServiceBrowser-_googlecast._tcp-118) [pychromecast.dial] Failed to determine cast type for host <unknown> (<urlopen error _ssl.c:1011: The handshake operation timed out>) (services:{MDNSServiceInfo(name='MagniFi-Max-91a8cdd7b0fc171d9133db4b0d27a010._googlecast._tcp.local.')})
2025-08-12 06:32:52.428 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.76 (192.168.0.76). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0)
2025-08-12 06:32:53.196 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.76 (192.168.0.76). Requested URL: '/api/websocket'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0)
2025-08-12 06:42:02.939 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.90 (192.168.0.90). Requested URL: '/auth/token'. (Home Assistant/2025.7.2 (io.robbie.HomeAssistant; build:2025.1356; iOS 18.6.0) Alamofire/5.8.0)
2025-08-12 06:42:03.004 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140520134392576] from 192.168.0.90 (Home Assistant/2025.7.2 (io.robbie.HomeAssistant; build:2025.1356; iOS 18.6.0)): Disconnected: Received close message during auth phase
2025-08-12 06:42:03.250 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140520134392736] from 192.168.0.90 (Home Assistant/2025.7.2 (io.robbie.HomeAssistant; build:2025.1356; iOS 18.6.0)): Unexpected error inside websocket API
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 350, in async_handle
    connection = await self._async_handle_auth_phase(auth, send_bytes_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 388, in _async_handle_auth_phase
    await send_bytes_text(AUTH_REQUIRED_MESSAGE)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/_websocket/writer.py", line 126, in send_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport
